name: Build and Package

on:
  push:
    branches: [ main ]
  release:
    types: [ created ]

jobs:
  build:
    strategy:
      matrix:
          include:
          - os: windows-latest
            preset: windows-release
            artifact: "*.exe"
          - os: ubuntu-latest
            preset: linux-release
            artifact: "*.deb"
          - os: macos-latest
            preset: mac-release
            artifact: "*.dmg"

    runs-on: ${{ matrix.os }}

    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          submodules: recursive
          
      - name: Install build tools (Linux)
        if: runner.os == 'Linux'
        run: |
          sudo apt-get update
          sudo apt-get install -y ninja-build gcc g++ make rpm
          echo "$(which ninja)" >> $GITHUB_PATH
 
      - name: Install build tools (macOS)
        if: runner.os == 'macOS'
        run: |
          brew install ninja
          echo "$(brew --prefix)/bin" >> $GITHUB_PATH
 
      - name: Install Ninja (Windows)
        if: runner.os == 'Windows'
        uses: seanmiddleditch/gha-setup-ninja@v4
 
      - name: Install vcpkg
        uses: lukka/run-vcpkg@v11
        with:
          runVcpkgInstall: true
 
      - name: Configure
        run: cmake --preset ${{ matrix.preset }}
 
      - name: Build
        run: cmake --build build/out --config Release
 
      - name: Package
        run: cd build/out && cpack
 
      - name: Upload installer
        uses: actions/upload-artifact@v4
        with:
          name: installer-${{ matrix.os }}
          path: build/out/${{ matrix.artifact }}
 